import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.github.schananas.java-conventions")
    kotlin("jvm") version "1.8.21"
}

dependencies {
    testImplementation("org.apache.maven:maven-compat:3.8.5")
    testImplementation("junit:junit:4.13.1")
    testImplementation("org.apache.maven.plugin-testing:maven-plugin-testing-harness:3.3.0")
    compileOnly("org.apache.maven:maven-plugin-api:3.8.5")
    compileOnly("org.apache.maven:maven-core:3.8.5")
    compileOnly("org.apache.maven:maven-artifact:3.8.5")
    compileOnly("org.apache.maven.plugin-tools:maven-plugin-annotations:3.6.0")
    implementation(kotlin("stdlib-jdk8"))
}

description = "hint"
repositories {
    mavenCentral()
}
val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "1.8"
}
val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "1.8"
}