import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.github.schananas.java-conventions")
    kotlin("jvm") version "1.8.21"
}

dependencies {
    implementation("io.projectreactor:reactor-core:3.5.4")
    implementation("io.projectreactor:reactor-test:3.5.4")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.14.2")
    implementation(kotlin("stdlib-jdk8"))
    api(project(":hint"))
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.2")
    testImplementation("io.projectreactor.tools:blockhound:1.0.7.RELEASE")
    testImplementation(kotlin("test"))
    implementation("org.jetbrains.kotlin:kotlin-test:1.8.20")
    implementation("org.jetbrains.kotlin:kotlin-test-junit:1.8.20")
}

description = "exercises"
repositories {
    mavenCentral()
}
val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "1.8"
}
val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "1.8"
}

tasks.test {
    useJUnitPlatform()
}